"""empty message

Revision ID: 1d0dbb9db28b
Revises: ed0f4653e758
Create Date: 2022-06-24 19:09:57.086359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0dbb9db28b'
down_revision = 'ed0f4653e758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=80), nullable=False),
    sa.Column('instansi', sa.String(length=100), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absen')
    # ### end Alembic commands ###
