"""empty message

Revision ID: 39f35b08584a
Revises: 3efc5096b838
Create Date: 2022-06-16 23:57:27.658967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f35b08584a'
down_revision = '3efc5096b838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_permit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('jenis_pekerjaan', sa.String(length=150), nullable=False),
    sa.Column('detail_pekerjaan', sa.String(length=150), nullable=False),
    sa.Column('lokasi', sa.String(length=50), nullable=False),
    sa.Column('nama_pengawas_pekerjaan', sa.String(length=50), nullable=False),
    sa.Column('nomor_pengawas_pekerjaan', sa.String(length=50), nullable=False),
    sa.Column('tanggal_mulai', sa.String(length=30), nullable=False),
    sa.Column('tanggal_selesai', sa.String(length=30), nullable=False),
    sa.Column('jam_mulai', sa.String(length=20), nullable=False),
    sa.Column('jam_selesai', sa.String(length=20), nullable=False),
    sa.Column('klasifikasi', sa.Text(), nullable=False),
    sa.Column('prosedur', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_permit')
    # ### end Alembic commands ###
