"""empty message

Revision ID: c403c618e20f
Revises: 1d0dbb9db28b
Create Date: 2022-07-19 11:33:58.392603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c403c618e20f'
down_revision = '1d0dbb9db28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nama', sa.VARCHAR(length=80), nullable=False),
    sa.Column('instansi', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telepon', sa.VARCHAR(length=20), nullable=False),
    sa.Column('foto', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
